# Generated by Django 5.2 on 2026-05-12 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.admin')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='usuarios.aluno')),
            ],
            options={
                'db_table': 'pergunta',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('pergunta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resposta', to='interacoes.pergunta')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='usuarios.professor')),
            ],
            options={
                'db_table': 'resposta',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('analisado', 'Analisado'), ('recusado', 'Recusado')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.admin')),
                ('pergunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interacoes.pergunta')),
                ('resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interacoes.resposta')),
            ],
        ),
    ]
