# Generated by Django 5.2 on 2026-05-15 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interacoes', '0001_initial'),
        ('usuarios', '0002_alter_perfil_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='denunciante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='usuarios.perfil'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('analisado', 'Analisado'), ('recusado', 'Recusado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.admin'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20),
        ),
    ]
