# Generated by Django 5.2 on 2026-05-25 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interacoes', '0002_initial'),
        ('usuarios', '0002_remove_perfil_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='analisado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='analisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_analisadas', to='usuarios.admin'),
        ),
    ]
