# Generated by Django 5.2 on 2026-05-25 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interacoes', '0003_inscricao_analisado_em_inscricao_analisado_por'),
        ('usuarios', '0002_remove_perfil_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='admin',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='analisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_analisadas', to='usuarios.admin'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='denunciado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='evidencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='parecer_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
