# Generated by Django 5.2 on 2026-06-11 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0004_alter_conteudo_professores'),
        ('interacoes', '0004_remove_denuncia_admin_remove_inscricao_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='resposta',
        ),
        migrations.AlterModelTable(
            name='denuncia',
            table='denuncia',
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('conteudo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='disciplinas.conteudo')),
            ],
            options={
                'db_table': 'forum',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='interacoes.forum')),
                ('resposta_para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='interacoes.mensagem')),
            ],
            options={
                'db_table': 'mensagem',
            },
        ),
        migrations.AddField(
            model_name='denuncia',
            name='mensagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interacoes.mensagem'),
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
