# Generated by Django 5.2 on 2026-05-12 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('carga_horaria', models.IntegerField()),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaPrerequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisitos', to='disciplinas.disciplina')),
                ('prerequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerida_por', to='disciplinas.disciplina')),
            ],
            options={
                'db_table': 'disciplina_prerequisito',
            },
        ),
    ]
