# Generated by Django 5.2 on 2026-05-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='disciplinaprerequisito',
            constraint=models.UniqueConstraint(fields=('disciplina', 'prerequisito'), name='unique_disciplina_prerequisito'),
        ),
    ]
