# Generated by Django 5.2 on 2026-05-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_remove_disciplina_carga_horaria_conteudo_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='materiais/'),
        ),
        migrations.AddField(
            model_name='material',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='nome',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vídeo'), ('imagem', 'Imagem'), ('link', 'Link Externo'), ('apresentacao', 'Apresentação'), ('documento', 'Documento')], default='link', max_length=20),
            preserve_default=False,
        ),
    ]
