# Generated by Django 5.2 on 2026-05-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0003_material_arquivo_material_descricao_material_link_and_more'),
        ('usuarios', '0003_professor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='conteudos', to='usuarios.professor'),
        ),
    ]
