# Generated by Django 5.2 on 2026-06-05 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0003_material_arquivo_material_descricao_material_link_and_more'),
        ('usuarios', '0002_remove_perfil_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteudos', to='disciplinas.disciplina'),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='conteudos', to='usuarios.professor'),
        ),
        migrations.AlterField(
            model_name='material',
            name='conteudo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='disciplinas.conteudo'),
        ),
    ]
