# Generated by Django 5.2 on 2026-06-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0003_material_arquivo_material_descricao_material_link_and_more'),
        ('usuarios', '0002_remove_perfil_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='conteudos', to='usuarios.professor'),
        ),
    ]
