# Generated by Django 5.2 on 2026-05-19 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('turmas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='professorturma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_lecionadas', to='usuarios.professor'),
        ),
        migrations.AddField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='disciplinas.disciplina'),
        ),
        migrations.AddField(
            model_name='professorturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_turmas', to='turmas.turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='turmas.turma'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('disciplina', 'nome'), name='unique_turma_por_disciplina'),
        ),
        migrations.AddConstraint(
            model_name='professorturma',
            constraint=models.UniqueConstraint(fields=('professor', 'turma'), name='unique_professor_turma'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('aluno', 'turma'), name='unique_aluno_turma'),
        ),
    ]
