# Generated by Django 5.2 on 2026-05-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_alter_disciplina_nome_and_more'),
        ('turmas', '0001_initial'),
        ('usuarios', '0002_alter_perfil_cpf'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('aluno', 'turma'), name='unique_aluno_turma'),
        ),
        migrations.AddConstraint(
            model_name='professorturma',
            constraint=models.UniqueConstraint(fields=('professor', 'turma'), name='unique_professor_turma'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('disciplina', 'nome'), name='unique_turma_por_disciplina'),
        ),
    ]
