# Generated by Django 5.2 on 2026-05-25 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_remove_disciplina_carga_horaria_conteudo_material'),
        ('turmas', '0002_initial'),
        ('usuarios', '0002_remove_perfil_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorturma',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='professorturma',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='turma',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='data_matricula',
            new_name='matriculado_em',
        ),
        migrations.AddField(
            model_name='matricula',
            name='conteudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='disciplinas.conteudo'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='ativa', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('aluno', 'conteudo'), name='unique_aluno_conteudo'),
        ),
        migrations.DeleteModel(
            name='ProfessorTurma',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
