# Generated by Django 5.2 on 2026-05-25 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_remove_professorturma_professor_and_more'),
    ]

    operations = [
        
    ]
