# Generated by Django 5.2 on 2026-05-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0005_remove_matricula_unique_aluno_turma'),
    ]

    operations = [
    
    ]
