# Generated by Django 5.2 on 2026-05-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0006_remove_matricula_unique_aluno_turma'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matricula',
            name='unique_aluno_turma',
        ),
    ]
