# Generated by Django 5.2 on 2026-06-05 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0004_disciplina_status_alter_conteudo_disciplina_and_more'),
        ('turmas', '0007_remove_matricula_unique_aluno_turma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada')], default='ativa', max_length=20),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='conteudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='disciplinas.conteudo'),
        ),
    ]
