# Generated by Django 5.2 on 2026-05-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0007_remove_matricula_unique_aluno_turma_and_more'),
    ]

    operations = [
    ]
