# Generated by Django 5.2 on 2026-05-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='role',
        ),
    ]
