# Generated by Django 5.2 on 2026-05-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='curriculos/'),
        ),
    ]
